tasks:
  install:
    image: node:carbon
    command:
      - yarn
    args:
      - install
  lint:
    image: node:carbon
    command:
      - yarn
    args:
      - lint
  test:
    image: node:carbon
    command:
      - yarn
    args:
      - test
security:
  image: allthings/nsp
workflow:
  - install
  - sail:parallel:
      - lint
      - test
      - security
